### ISSUE TITLE
inference --input missing value

### ISSUE THREAD

**Issue by chikiuso** [Sindhu-Hegde/pseudo-visual-speech-denoising#2]
Thank for your quick response in last issue @Rudrabha !! you are always doing great projects! I tried to run the inference and showed the following message, thanks : 

  File "/usr/local/lib/python3.7/dist-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/lib/python3.7/dist-packages/soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/usr/local/lib/python3.7/dist-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'tmp.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 274, in <module>
    predict(args)
  File "inference.py", line 174, in predict
    inp_wav = load_wav(args)
  File "inference.py", line 22, in load_wav
    wav = audio.load_wav(wav_file, sampling_rate)
  File "/root/pseudo-visual-speech-denoising/audio/audio_utils.py", line 7, in load_wav
    return librosa.core.load(path, sr=sr)[0]
  File "/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py", line 142, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py", line 164, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "/usr/local/lib/python3.7/dist-packages/audioread/__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "/usr/local/lib/python3.7/dist-packages/audioread/rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'tmp.wav'

**Comment by Sindhu-Hegde** [comment]
Did you give the input noisy file in the arguments? Try giving any noisy audio/video files by specifying --input=<filepath>

python inference.py --lipsync_student_model_path=<trained-student-model-ckpt-path> --checkpoint_path=<trained-denoising-model-ckpt-path> --input=<noisy-audio/video-file>

**Comment by chikiuso** [comment]
sorry my mistake, I forgot to add ./ , thanks.
