### ISSUE TITLE
tmp.waw and temp.wav

### ISSUE THREAD

**Issue by Tyson-svg** [Sindhu-Hegde/pseudo-visual-speech-denoising#7]
what are these tmp.wav and temp.wav in inference.py
i am getting no such file or directory when i try to denoise using pretrained models given by you

i had given  
 python inference.py --lipsync_student_model_path=<"C:\Users\savdo\OneDrive\Desktop\major\pseudo-visual-speech
-denoising-main\lipsync\checkpoints\lipsync_student.pth"> --checkpoint_path=<"C:\Users\savdo\OneDrive\Desktop\major\pseudo-visual-speech-denoising-main\checkpoints\denoising.pt"> --input=
<"C:\Users\savdo\OneDrive\Desktop\major\pseudo-visual-speech-denoising-main\timit_3spk.wav">

but i am getting this as an error(Please help me)

The system cannot find the file specified.
C:\Users\savdo\AppData\Local\Programs\Python\Python39\lib\site-packages\librosa\util\decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
Traceback (most recent call last):
  File "C:\Users\savdo\AppData\Local\Programs\Python\Python39\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Users\savdo\AppData\Local\Programs\Python\Python39\lib\site-packages\soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\savdo\AppData\Local\Programs\Python\Python39\lib\site-packages\soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "C:\Users\savdo\AppData\Local\Programs\Python\Python39\lib\site-packages\soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'C:\\Users\\savdo\\OneDrive\\Desktop\\major\\pseudo-visual-speech-denoising-main\\timit_3spk.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\savdo\OneDrive\Desktop\major\pseudo-visual-speech-denoising-main\inference.py", line 292, in <module>
    predict(args)
  File "C:\Users\savdo\OneDrive\Desktop\major\pseudo-visual-speech-denoising-main\inference.py", line 175, in predict
    inp_wav = load_wav(args)
  File "C:\Users\savdo\OneDrive\Desktop\major\pseudo-visual-speech-denoising-main\inference.py", line 22, in load_wav
    wav = audio.load_wav(wav_file, sampling_rate)
  File "C:\Users\savdo\OneDrive\Desktop\major\pseudo-visual-speech-denoising-main\audio\audio_utils.py", line 8, in load_wav
    return librosa.core.load(path, sr=sr)[0]
  File "C:\Users\savdo\AppData\Local\Programs\Python\Python39\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\savdo\AppData\Local\Programs\Python\Python39\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Users\savdo\AppData\Local\Programs\Python\Python39\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Users\savdo\AppData\Local\Programs\Python\Python39\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "C:\Users\savdo\AppData\Local\Programs\Python\Python39\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\savdo\\OneDrive\\Desktop\\major\\pseudo-visual-speech-denoising-main\\timit_3spk.wav'

**Comment by Sindhu-Hegde** [comment]
Hi, the error says that there is an issue in opening your input file; your input file is not present in the path you have provided: `FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\savdo\OneDrive\Desktop\major\pseudo-visual-speech-denoising-main\timit_3spk.wav`
Make sure that your input file exists, the path that you provide is appropriate and it is not corrupted.
